name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Triggers deployment when code is pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Frontend Deployment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Dependencies
        working-directory: ./acquired-beauty-app
        run: npm install

      - name: Build Frontend
        working-directory: ./acquired-beauty-app
        run: npm run dev

      - name: Deploy Frontend to Vercel
        working-directory: ./acquired-beauty-app
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod --token $VERCEL_TOKEN
